create table if not exists public.blog_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.blog_categories (name, display_order)
values
  ('Systems', 10),
  ('Automation', 20),
  ('Developer Experience', 30),
  ('Product Engineering', 40)
on conflict (name) do update
set display_order = excluded.display_order,
    is_active = true;

alter table public.blog_categories enable row level security;

drop policy if exists "Anyone can read active blog categories" on public.blog_categories;
create policy "Anyone can read active blog categories"
  on public.blog_categories
  for select
  using (is_active = true);

drop policy if exists "Admins can insert blog categories" on public.blog_categories;
create policy "Admins can insert blog categories"
  on public.blog_categories
  for insert
  to authenticated
  with check (public.is_admin());

drop policy if exists "Admins can update blog categories" on public.blog_categories;
create policy "Admins can update blog categories"
  on public.blog_categories
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());
